### ISSUE TITLE
Stopped working after the update

### ISSUE THREAD

**Issue by Ciana1220** [christopher-chandler/Bulk_Generate_Japanese_Vocab_Frequency#2]
**Hello, an error occurred after I used 'bulk generate vocabulary frequency'**

Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-07-08 17:34:43

Caught exception:
Traceback (most recent call last):
  File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 230, in <lambda>
    bulk_generate_frequency.triggered.connect(lambda _, brow=browser: on_bulk_generate_vocab(brow))
  File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 240, in on_bulk_generate_vocab
    bulk_generate_vocab_frequency_fg(browser.selectedNotes())
  File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 86, in bulk_generate_vocab_frequency_fg
    reload_json_config()
  File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 53, in reload_json_config
    word_type_field = config["03_word_type_output_field"]
KeyError: '03_word_type_output_field'

**This is my configuration, it was working before the update**

![config ankilo](https://github.com/christopher-chandler/bulk_generate_japanese_vocab_frequency/assets/122986073/0d59d86a-6d37-48a2-9907-5ea8ed141d64)

**Comment by christopher-chandler** [comment]
hey, a new field called "word type" has been added. I am not sure why this is not reflected in your config file. I guess anki did not add it. Either try uninstalling the add-on and seeing if you get the field in the config file after reinstallation or manually add it the config file. Please check the read me about the new field and how it works. I hope this helps. if not, let me know.

**Comment by Ciana1220** [comment]
Hi

**I reinstalled the addon and a new error appeared**

Caught exception:
Traceback (most recent call last):
  File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 230, in <lambda>
    bulk_generate_frequency.triggered.connect(lambda _, brow=browser: on_bulk_generate_vocab(brow))
  File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 240, in on_bulk_generate_vocab
    bulk_generate_vocab_frequency_fg(browser.selectedNotes())
  File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 87, in bulk_generate_vocab_frequency_fg
    freq_db = sqlite3.connect(freq_dict)
sqlite3.OperationalError: unable to open database file

**my configuration:**

![erro2](https://github.com/christopher-chandler/bulk_generate_japanese_vocab_frequency/assets/122986073/2e320b0f-549f-475f-a2c3-82d6cebbe9c6)


**I noticed that unlike the example photo you posted, the 'freq_dict' field was missing. I added it to this configuration, but it didn't solve the problem.**

**Maybe the problem is my Anki version? I am using version 2.1.65. I could update my version if that would solve the problem**

**Comment by christopher-chandler** [comment]
I don't think that that is an issue, but you can try it. I tested everything before hand, but I will test on some other computers too. 
Could you check the add on files on your computer to see if it downloaded the databases?
It could be that they are missing.

**Comment by Ciana1220** [comment]
I checked, apparently everything is fine

![data](https://github.com/christopher-chandler/bulk_generate_japanese_vocab_frequency/assets/122986073/a6a4d1fd-7fb4-4694-9506-67e971aa912a)

**Comment by christopher-chandler** [comment]
try with the following deck and note type [test.apkg.zip](https://github.com/user-attachments/files/16144235/test.apkg.zip)

Try with this config. I was having problem with single slashes. So, I used doubled ones. 
```
{
    "01_note_type": "Japanese",
    "02_vocab_input_field": "Target Word",
    "03_frequency_output_field": "Frequency Ranking",
    "03_word_type_output_field": "Word Type",
    "04_overwrite_destination_field": true,
    "0_freq_dict": "C:\\Users\\ls\\AppData\\Roaming\\Anki2\\addons21\\1004691625\\databases\\freq_dict.db",
    "0_jm_dict": "C:\\Users\\ls\\AppData\\Roaming\\Anki2\\addons21\\1004691625\\databases\\jmdict.db"
}
```

**Comment by christopher-chandler** [comment]
I updated the comment.

**Comment by christopher-chandler** [comment]
> Hi
> 
> **I reinstalled the addon and a new error appeared**
> 
> Caught exception: Traceback (most recent call last): File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 230, in bulk_generate_frequency.triggered.connect(lambda _, brow=browser: on_bulk_generate_vocab(brow)) File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 240, in on_bulk_generate_vocab bulk_generate_vocab_frequency_fg(browser.selectedNotes()) File "C:\Users\LS\AppData\Roaming\Anki2\addons21\1004691625\main.py", line 87, in bulk_generate_vocab_frequency_fg freq_db = sqlite3.connect(freq_dict) sqlite3.OperationalError: unable to open database file
> 
> **my configuration:**
> 
> ![erro2](https://private-user-images.githubusercontent.com/122986073/346969591-2e320b0f-549f-475f-a2c3-82d6cebbe9c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzM5MDQsIm5iZiI6MTcyMDUzMzYwNCwicGF0aCI6Ii8xMjI5ODYwNzMvMzQ2OTY5NTkxLTJlMzIwYjBmLTU0OWYtNDc1Zi1hMmMzLTgyZDZjZWJiZTljNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxNDAwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDA4MDdjNjIxZDg1Mjg1YzA0YjI2Yjk3YTI5ZjNlNTJhNjY4OTUwNDAyZjI1OWExN2RmYzMwNTg3NzljNjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JWzGTEvC9z4K2jCqbCAmTkSAgkgyJLcoKhJl9W8QJWQ)
> 
> **I noticed that unlike the example photo you posted, the 'freq_dict' field was missing. I added it to this configuration, but it didn't solve the problem.**
> 
> **Maybe the problem is my Anki version? I am using version 2.1.65. I could update my version if that would solve the problem**

The file path my not be correct or the database might be opened up by another program (on accident). Check your task manager if some other program is accessing the database or if you have multiple instances of anki running in the background.

**Comment by Ciana1220** [comment]
It still doesn't work, I couldn't find any problem. I really don't know what it could be, I've been using this addon for months without any issues and after the update it started giving errors. If the addon is only giving me problems, then it must be something on my PC. I'll check it out later and let you know if I find anything. I appreciate you trying to help me.

**Comment by christopher-chandler** [comment]
The only things that I can offer is an older version of the add on or I can look at your computer personally via zoom or google meets and debug it there.

**Comment by Ciana1220** [comment]
I hadn't seen the suggestion to use \\ in my configuration. I tried it right now and it worked. I appreciate you helping me.

**Comment by Ciana1220** [comment]
> try with the following deck and note type [test.apkg.zip](https://github.com/user-attachments/files/16144235/test.apkg.zip)
> 
> Try with this config. I was having problem with single slashes. So, I used doubled ones.
> 
> ```
> {
>     "01_note_type": "Japanese",
>     "02_vocab_input_field": "Target Word",
>     "03_frequency_output_field": "Frequency Ranking",
>     "03_word_type_output_field": "Word Type",
>     "04_overwrite_destination_field": true,
>     "0_freq_dict": "C:\\Users\\ls\\AppData\\Roaming\\Anki2\\addons21\\1004691625\\databases\\freq_dict.db",
>     "0_jm_dict": "C:\\Users\\ls\\AppData\\Roaming\\Anki2\\addons21\\1004691625\\databases\\jmdict.db"
> }
> ```

**This configuration worked, thank you**

**Comment by christopher-chandler** [comment]
perfect! could you please comment the add on accordingly so that others can see how you solved the problem. Also, please star this repo and like the add on website, if you haven't. That would mean a lot to me. If you have any suggestions for the the addon, please let me know!
